services:
  vpn_zi_sing_box_server:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
      - /etc/sing-box:/app/sing-box
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - vpn_zi_sing_box_server
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/staticfiles:/staticfiles:ro
    restart: unless-stopped
