services:
  vpn_zi_sing_box_server:
    build: .
    image: vpn_zi_sing_box_server
    env_file: .env
    volumes:
      # код и миграции
      - ./app:/app
      # данные (БД, статика и тд.)   
      - ./data:/data
      # директория с sing-box конфигурацией
      - /etc/sing-box:/sing-box
    ports:
      - "8000:8000"
    
    # Временная папка для Gunicorn/Django temp files
    tmpfs:
      - /tmp:size=50M
      
    # Для безопасности
    cap_drop:
      - ALL           # УДАЛЯЕТ ВСЕ 14 стандартных привилегий
    cap_add:
      - CHOWN         # ДОБАВЛЯЕТ ТОЛЬКО "менять владельца файлов"

    read_only: true
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - vpn_zi_sing_box_server
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/staticfiles:/data/staticfiles:ro
    restart: unless-stopped
