services:
  sing_box_server:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
      - /etc/sing-box/config.json:/app/data/singbox.json
    ports:
      - "8001:8001"
    privileged: true