services:
  vpn_zi_sing_box_server:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
      - /etc/sing-box:/app/sing-box
    restart: unless-stopped
    networks:
      - vpn_zi_network

networks:
  vpn_zi_network:
    external: true
