services:
  vpn_zi_sing_box_server:
    build: .
    image: vpn_zi_sing_box_server
    env_file: .env
    volumes:
      # код и миграции
      - ./app:/app
      # данные (БД, статика и тд.)   
      - ./data:/data
      # директория с sing-box конфигурацией
      - /etc/sing-box:/sing-box
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - vpn_zi_sing_box_server
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/staticfiles:/data/staticfiles:ro
    restart: unless-stopped
